name: Publish NPM Version Info

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: Han-Haocheng/lx-music-rev-version-info # TODO: 换成你自己的版本信息仓库，没有就删除此 workflow
          event-type: npm-release
